[package]
name = "inimeg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.0"
clap = { version = "4.5.56", features = ["derive"] }
rustls = "0.23.36"
thiserror = "2.0.18"
url = "2.5.8"

[dev-dependencies]
rstest = "0.26.1"
